services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - web
    restart:
      on-failure

  web:
    build: .
    env_file: .env
    environment:
      - DB_HOST=db
    volumes:
      - media_data:/app/media
      - static_data:/app/static
    expose:
      - 8000
    command: bash -c "poetry run python manage.py migrate && poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    restart:
      on-failure

  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    restart:
      on-failure


networks:
  default:

volumes:
  postgres_data:
  media_data:
  static_data:
