# Generated by Django 5.2.1 on 2025-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainnode',
            name='node_level',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='chainnode',
            name='node_type',
            field=models.CharField(choices=[('factory', 'Завод'), ('retail', 'Розничная сеть'),
                                            ('entrepreneur', 'Индивидуальный предприниматель')], default=1),
            preserve_default=False,
        ),
    ]
