# Generated by Django 5.2.1 on 2025-05-27 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_chain', '0002_chainnode_node_level_chainnode_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainnode',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='retail_chain.contacts', unique=True),
        ),
    ]
