# Generated by Django 5.2.1 on 2025-05-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('retail_chain', '0003_alter_chainnode_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainnode',
            name='payment_arrears',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='chainnode',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
    ]
