# Generated by Django 5.2.1 on 2025-05-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('retail_chain', '0004_alter_chainnode_payment_arrears_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainnode',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
